# Generated by Django 5.0.6 on 2024-05-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='box_office_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
