# Generated by Django 5.0.6 on 2024-05-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_audience_cnt_movie_backdrop_path_movie_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='audience_accumulate',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
