# Generated by Django 5.0.6 on 2024-05-28 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('movies', '0004_movie_audience_accumulate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='audience_accumulate',
        ),
        migrations.AddField(
            model_name='movie',
            name='stills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='credits',
            field=models.ManyToManyField(through='movies.MovieActor', to='actors.actor'),
        ),
    ]
