# Generated by Django 5.0.6 on 2024-06-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movie_backdrop_path_movie_audience_accumulate'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
