# Generated by Django 5.0.6 on 2024-06-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_runtime_movie_trailers'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='review_videoes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
