# Generated by Django 5.0.6 on 2024-06-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_rename_comment_review_text_alter_review_movie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="date_watched",
            field=models.DateField(blank=True, null=True),
        ),
    ]
