# Generated by Django 5.0.6 on 2024-06-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0005_alter_review_movie_alter_review_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
