# Generated by Django 5.0.6 on 2024-08-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0006_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
