# Generated by Django 5.0.6 on 2024-11-10 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomTicket",
            fields=[
                (
                    "custom_ticket_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("ticket_image", models.TextField()),
                (
                    "hologram_color1",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "hologram_color2",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("comment", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
